# Generated by Django 5.0.6 on 2025-03-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("email", models.CharField(max_length=60)),
                ("message", models.TextField(max_length=100000)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
