# Generated by Django 5.0.6 on 2025-03-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_guestentry_delete_info"),
    ]

    operations = [
        migrations.RenameField(
            model_name="guestentry",
            old_name="submitted_at",
            new_name="created_at",
        ),
        migrations.AlterField(
            model_name="guestentry",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="guestentry",
            name="message",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="guestentry",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
