# Generated by Django 5.0.6 on 2025-03-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_rename_submitted_at_guestentry_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="guestentry",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
